configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-hidden-salad-72713969.us-east-2.aws.neon.tech/neondb?user=rokas.company.test.email&password=upawHfOYDS73
  - configuration:
      name: auth_config
      client_id: a6fc822d8a694e9c93eef9d7cd43c41e
      client_secret: 51ed12b73401401e90e8320896100d53
